# Default values for chart
web:
  name: rating-web
  deployment: rating-web-prod
  versionLabel: prod
  replicas: 1
  image: "squillace.azurecr.io/squillace/rating-web"
  imageTag: "latest"
  serviceType: "LoadBalancer"